
version: '3.8'

services:
  sage:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: sage-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgres://postgres:postgres@db:5432/sage}
      - NODE_ENV=${NODE_ENV:-production}
      - SMTP_SERVER=${SMTP_SERVER:-}
      - SMTP_PORT=${SMTP_PORT:-}
      - SMTP_USER=${SMTP_USER:-}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-}
      - SMTP_FROM=${SMTP_FROM:-}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_REGION=${AWS_REGION:-}
      - S3_BUCKET=${S3_BUCKET:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    networks:
      - sage-network
    volumes:
      - sage-logs:/app/logs
      - sage-data:/app/data
      - sage-executions:/app/executions
      - sage-tmp:/app/tmp
      - ./init-scripts:/app/init-scripts

networks:
  sage-network:
    driver: bridge

volumes:
  sage-logs:
    driver: local
  sage-data:
    driver: local
  sage-executions:
    driver: local
  sage-tmp:
    driver: local
